/*
 * TurboQuant — KV Cache Compression
 *
 * Pure C, no dependencies beyond math.h and stdlib.h.
 * Codebooks are precomputed (from Python Lloyd-Max solver).
 */

#include "turboquant.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>

/* ================================================================
 * Precomputed Lloyd-Max codebooks
 * Generated by: lloyd_max_codebook(dim, nbits) in Python
 * ================================================================ */

/* dim=128, 4-bit */
static const float BOUNDS_128_4[] = {
    -1.0f, -0.2093757540f, -0.1614574343f, -0.1261821389f, -0.0966815352f,
    -0.0704018921f, -0.0460341796f, -0.0227645691f, 0.0f,
    0.0227645691f, 0.0460341796f, 0.0704018921f, 0.0966815352f,
    0.1261821389f, 0.1614574343f, 0.2093757540f, 1.0f
};
static const float LEVELS_128_4[] = {
    -0.2377767116f, -0.1809660643f, -0.1419393122f, -0.1104155704f,
    -0.0829389691f, -0.0578577779f, -0.0342055745f, -0.0113209626f,
    0.0113209626f, 0.0342055745f, 0.0578577779f, 0.0829389691f,
    0.1104155704f, 0.1419393122f, 0.1809660643f, 0.2377767116f
};

/* dim=128, 3-bit */
static const float BOUNDS_128_3[] = {
    -1.0f, -0.1532684714f, -0.0923626870f, -0.0440949611f, 0.0f,
    0.0440949611f, 0.0923626870f, 0.1532684714f, 1.0f
};
static const float LEVELS_128_3[] = {
    -0.1883971840f, -0.1181397662f, -0.0665856078f, -0.0216043107f,
    0.0216043107f, 0.0665856078f, 0.1181397662f, 0.1883971840f
};

/* dim=128, 2-bit */
static const float BOUNDS_128_2[] = {
    -1.0f, -0.0865165591f, 0.0f, 0.0865165591f, 1.0f
};
static const float LEVELS_128_2[] = {
    -0.1330415159f, -0.0399915949f, 0.0399915949f, 0.1330415159f
};

/* dim=256, 4-bit */
static const float BOUNDS_256_4[] = {
    -1.0f, -0.1491028965f, -0.1147549003f, -0.0895837694f, -0.0685906038f,
    -0.0499228649f, -0.0326334760f, -0.0161349699f, 0.0f,
    0.0161349699f, 0.0326334760f, 0.0499228649f, 0.0685906038f,
    0.0895837694f, 0.1147549003f, 0.1491028965f, 1.0f
};
static const float LEVELS_256_4[] = {
    -0.1695038378f, -0.1286947727f, -0.1008072942f, -0.0783526227f,
    -0.0588216707f, -0.0410183705f, -0.0242445413f, -0.0080232974f,
    0.0080232974f, 0.0242445413f, 0.0410183705f, 0.0588216707f,
    0.0783526227f, 0.1008072942f, 0.1286947727f, 0.1695038378f
};

/* dim=256, 3-bit */
static const float BOUNDS_256_3[] = {
    -1.0f, -0.1088098735f, -0.0654660836f, -0.0312320981f, 0.0f,
    0.0312320981f, 0.0654660836f, 0.1088098735f, 1.0f
};
static const float LEVELS_256_3[] = {
    -0.1338542849f, -0.0837654546f, -0.0471667089f, -0.0152974874f,
    0.0152974874f, 0.0471667089f, 0.0837654546f, 0.1338542849f
};

/* dim=256, 2-bit */
static const float BOUNDS_256_2[] = {
    -1.0f, -0.0612631887f, 0.0f, 0.0612631887f, 1.0f
};
static const float LEVELS_256_2[] = {
    -0.0942377821f, -0.0282885991f, 0.0282885991f, 0.0942377821f
};

/* ================================================================
 * Simple xoshiro256** PRNG for deterministic rotation matrices
 * ================================================================ */

typedef struct { uint64_t s[4]; } rng_state;

static inline uint64_t rotl(uint64_t x, int k) {
    return (x << k) | (x >> (64 - k));
}

static uint64_t rng_next(rng_state *rng) {
    uint64_t *s = rng->s;
    uint64_t result = rotl(s[1] * 5, 7) * 9;
    uint64_t t = s[1] << 17;
    s[2] ^= s[0]; s[3] ^= s[1]; s[1] ^= s[2]; s[0] ^= s[3];
    s[2] ^= t; s[3] = rotl(s[3], 45);
    return result;
}

static void rng_seed(rng_state *rng, uint64_t seed) {
    /* SplitMix64 to initialize state from a single seed */
    for (int i = 0; i < 4; i++) {
        seed += 0x9e3779b97f4a7c15ULL;
        uint64_t z = seed;
        z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
        z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
        rng->s[i] = z ^ (z >> 31);
    }
}

/* Standard normal via Box-Muller */
static float rng_normal(rng_state *rng) {
    double u1 = (double)(rng_next(rng) >> 11) / (double)(1ULL << 53);
    double u2 = (double)(rng_next(rng) >> 11) / (double)(1ULL << 53);
    if (u1 < 1e-15) u1 = 1e-15;
    return (float)(sqrt(-2.0 * log(u1)) * cos(2.0 * M_PI * u2));
}

/* ================================================================
 * Gram-Schmidt QR decomposition (for generating orthogonal R)
 * ================================================================ */

static void gram_schmidt(float *R, int dim) {
    /* R is dim x dim, row-major. Orthogonalize rows in-place. */
    for (int i = 0; i < dim; i++) {
        float *ri = R + i * dim;

        /* Subtract projections onto previous rows */
        for (int j = 0; j < i; j++) {
            float *rj = R + j * dim;
            float dot = 0.0f;
            for (int k = 0; k < dim; k++) dot += ri[k] * rj[k];
            for (int k = 0; k < dim; k++) ri[k] -= dot * rj[k];
        }

        /* Normalize */
        float norm = 0.0f;
        for (int k = 0; k < dim; k++) norm += ri[k] * ri[k];
        norm = sqrtf(norm);
        if (norm > 1e-10f) {
            float inv = 1.0f / norm;
            for (int k = 0; k < dim; k++) ri[k] *= inv;
        }
    }
}

/* ================================================================
 * Core API
 * ================================================================ */

static int set_codebook(tq_ctx *ctx, int dim, int nbits) {
    const float *b = NULL, *l = NULL;
    int nb = 0, nl = 0;

    #define CASE(D, N) \
        if (dim == D && nbits == N) { \
            b = BOUNDS_##D##_##N; nb = sizeof(BOUNDS_##D##_##N)/sizeof(float); \
            l = LEVELS_##D##_##N; nl = sizeof(LEVELS_##D##_##N)/sizeof(float); \
        }

    CASE(128, 2) CASE(128, 3) CASE(128, 4)
    CASE(256, 2) CASE(256, 3) CASE(256, 4)
    #undef CASE

    if (!b || !l) return -1;

    ctx->n_levels = nl;
    memcpy(ctx->boundaries, b, nb * sizeof(float));
    memcpy(ctx->levels, l, nl * sizeof(float));
    return 0;
}

int tq_init(tq_ctx *ctx, int dim, int nbits, uint64_t seed) {
    if (dim > TQ_MAX_DIM || nbits < 2 || nbits > 5)
        return -1;

    ctx->dim = dim;
    ctx->nbits = nbits;

    /* Set codebook */
    if (set_codebook(ctx, dim, nbits) != 0)
        return -1;

    /* Packed bytes: ceil(dim * nbits / 8) */
    ctx->packed_bytes = (dim * nbits + 7) / 8;

    /* Generate random orthogonal matrix via Gaussian + Gram-Schmidt */
    ctx->R = (float *)malloc(dim * dim * sizeof(float));
    if (!ctx->R) return -1;

    rng_state rng;
    rng_seed(&rng, seed);
    for (int i = 0; i < dim * dim; i++)
        ctx->R[i] = rng_normal(&rng);

    gram_schmidt(ctx->R, dim);
    return 0;
}

void tq_free(tq_ctx *ctx) {
    free(ctx->R);
    ctx->R = NULL;
}

/* Find which quantization bin a value falls into (binary search) */
static inline int bucketize(float x, const float *bounds, int n_bounds) {
    /* bounds has n_levels+1 entries. We search bounds[1..n_levels-1]. */
    int lo = 0, hi = n_bounds - 2;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (x < bounds[mid + 1])
            hi = mid - 1;
        else
            lo = mid + 1;
    }
    return lo;
}

void tq_encode(const tq_ctx *ctx, const float *vec,
               uint8_t *packed, float *norm) {
    int dim = ctx->dim;
    int nbits = ctx->nbits;
    int n_levels = ctx->n_levels;

    /* 1. Compute norm */
    float n = 0.0f;
    for (int i = 0; i < dim; i++) n += vec[i] * vec[i];
    n = sqrtf(n);
    *norm = n;

    if (n < 1e-10f) {
        memset(packed, 0, ctx->packed_bytes);
        return;
    }

    /* 2. Normalize */
    float inv_n = 1.0f / n;

    /* 3. Rotate and 4. Quantize (fused to avoid temp buffer) */
    /* Clear output */
    memset(packed, 0, ctx->packed_bytes);

    for (int i = 0; i < dim; i++) {
        /* Compute rotated coordinate i: dot(R[i], unit_vec) */
        const float *ri = ctx->R + i * dim;
        float rot = 0.0f;
        for (int j = 0; j < dim; j++)
            rot += ri[j] * vec[j] * inv_n;

        /* Quantize: find bin */
        int idx = bucketize(rot, ctx->boundaries, n_levels + 1);
        if (idx < 0) idx = 0;
        if (idx >= n_levels) idx = n_levels - 1;

        /* Pack into output */
        if (nbits == 4) {
            /* 2 indices per byte */
            int byte_idx = i / 2;
            if (i % 2 == 0)
                packed[byte_idx] |= (uint8_t)(idx & 0x0F);
            else
                packed[byte_idx] |= (uint8_t)((idx & 0x0F) << 4);
        } else if (nbits == 2) {
            /* 4 indices per byte */
            int byte_idx = i / 4;
            int shift = (i % 4) * 2;
            packed[byte_idx] |= (uint8_t)((idx & 0x03) << shift);
        } else if (nbits == 3) {
            /* Bit-level packing for 3-bit */
            int bit_pos = i * 3;
            int byte_idx = bit_pos / 8;
            int bit_off = bit_pos % 8;
            packed[byte_idx] |= (uint8_t)((idx & 0x07) << bit_off);
            if (bit_off > 5) /* overflow into next byte */
                packed[byte_idx + 1] |= (uint8_t)((idx & 0x07) >> (8 - bit_off));
        }
    }
}

void tq_decode(const tq_ctx *ctx, const uint8_t *packed,
               float norm, float *out) {
    int dim = ctx->dim;
    int nbits = ctx->nbits;
    int n_levels = ctx->n_levels;

    /* 1. Unpack indices and lookup codebook values into temp */
    float rotated[TQ_MAX_DIM];

    for (int i = 0; i < dim; i++) {
        int idx = 0;

        if (nbits == 4) {
            int byte_idx = i / 2;
            if (i % 2 == 0)
                idx = packed[byte_idx] & 0x0F;
            else
                idx = (packed[byte_idx] >> 4) & 0x0F;
        } else if (nbits == 2) {
            int byte_idx = i / 4;
            int shift = (i % 4) * 2;
            idx = (packed[byte_idx] >> shift) & 0x03;
        } else if (nbits == 3) {
            int bit_pos = i * 3;
            int byte_idx = bit_pos / 8;
            int bit_off = bit_pos % 8;
            idx = (packed[byte_idx] >> bit_off) & 0x07;
            if (bit_off > 5)
                idx |= (packed[byte_idx + 1] << (8 - bit_off)) & 0x07;
        }

        if (idx >= n_levels) idx = n_levels - 1;
        rotated[i] = ctx->levels[idx];
    }

    /* 2. Inverse rotation: out = R^T @ rotated (R is orthogonal) */
    for (int j = 0; j < dim; j++) {
        float sum = 0.0f;
        for (int i = 0; i < dim; i++)
            sum += ctx->R[i * dim + j] * rotated[i];  /* R^T[j][i] = R[i][j] */
        out[j] = sum * norm;
    }
}

float tq_compression_ratio(const tq_ctx *ctx) {
    int baseline = ctx->dim * 4;  /* float32 */
    int compressed = tq_bytes_per_vector(ctx);
    return (float)baseline / (float)compressed;
}

int tq_bytes_per_vector(const tq_ctx *ctx) {
    return ctx->packed_bytes + 2;  /* packed indices + float16 norm */
}
